In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization
import matplotlib.pyplot as plt
import os
import glob

2024-06-28 13:46:54.623079: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-28 13:46:57.220578: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
from os import listdir
from os.path import isfile, join

dataset = pd.concat(map(pd.read_csv, glob.glob('/mnt/c/Users/aardp/Downloads/G3/*.csv')))
dataset.head()

/tmp/ipykernel_33523/1150708094.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  dataset = pd.concat(map(pd.read_csv, glob.glob('/mnt/c/Users/aardp/Downloads/G3/*.csv')))

,Year/Month,Box Size,Longitude,Latitude,PID2: Standard/Enhanced,Group,Checksum,S-S1,S-Median,S-S5,...,R-S1,R-Median,R-S5,R-Mean,R-Observation number,R-Standard deviation,R-Mean day of the month,R-Fraction of daylight observations,R-Mean Longitude,R-Mean Latitude
0,1857/1,2,276.0,6.0,0,3,14,26.10,26.1,26.1,...,65.6,65.6,65.6,65.6,1,0.0,16,1.0,0.8,0.8
0,1858/1,2,352.0,44.0,0,3,7,11.70,11.7,11.7,...,91.6,91.6,91.6,91.6,1,0.0,18,0.0,0.1,0.8
1,1858/1,2,334.0,8.0,0,3,8,25.00,25.6,25.6,...,83.4,83.4,83.4,83.4,1,0.0,26,0.0,0.3,0.2
0,1858/2,2,302.0,24.0,0,3,2,21.10,21.1,21.1,...,58.9,58.9,58.9,58.9,1,0.0,24,0.0,0.6,0.3
1,1858/2,2,332.0,10.0,0,3,4,23.67,23.9,25.7,...,66.4,66.4,66.4,66.4,1,0.0,10,1.0,0.3,0.0

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5078925 entries, 0 to 4466
Data columns (total 47 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Year/Month                           object
 1   Box Size                             object
 2   Longitude                            float64
 3   Latitude                             float64
 4   PID2: Standard/Enhanced              object
 5   Group                                object
 6   Checksum                             object
 7   S-S1                                 float64
 8   S-Median                             float64
 9   S-S5                                 float64
 10  S-Mean                               float64
 11  S-Observation number                 object
 12  S-Standard deviation                 float64
 13  S-Mean day of the month              object
 14  S-Fraction of daylight observations  float64
 15  S-Mean Longitude                     float64
 16  S-Mean Latitude                      float64
 17  A-S1                                 float64
 18  A-Median                             float64
 19  A-S5                                 float64
 20  A-Mean                               float64
 21  A-Observation number                 object
 22  A-Standard deviation                 float64
 23  A-Mean day of the month              object
 24  A-Fraction of daylight observations  float64
 25  A-Mean Longitude                     float64
 26  A-Mean Latitude                      float64
 27  Q-S1                                 float64
 28  Q-Median                             float64
 29  Q-S5                                 float64
 30  Q-Mean                               float64
 31  Q-Observation number                 object
 32  Q-Standard deviation                 float64
 33  Q-Mean day of the month              object
 34  Q-Fraction of daylight observations  float64
 35  Q-Mean Longitude                     float64
 36  Q-Mean Latitude                      float64
 37  R-S1                                 float64
 38  R-Median                             float64
 39  R-S5                                 float64
 40  R-Mean                               float64
 41  R-Observation number                 object
 42  R-Standard deviation                 float64
 43  R-Mean day of the month              object
 44  R-Fraction of daylight observations  float64
 45  R-Mean Longitude                     float64
 46  R-Mean Latitude                      float64
dtypes: float64(34), object(13)
memory usage: 1.8+ GB

In [4]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
print(tf.config.list_physical_devices('GPU'))

Num GPUs Available:  1
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

2024-06-28 13:48:13.348265: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-28 13:48:13.899320: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-28 13:48:13.899390: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:07:00.0/numa_node
Your kernel may have been built without NUMA support.

In [ ]:
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # Suppress TensorFlow warnings

# Load the data
df = dataset

# Display the first few rows of the dataframe
print(df.head())

# Display information about the dataframe
print(df.info())

# Display statistical summary
print(df.describe())

# Check for any remaining NaN values
print(df.isna().sum())

# Remove rows with NaN values (if any)
df.dropna(inplace=True)

# Extract temporal features from 'Year/Month'
df['Year/Month'] = pd.to_datetime(df['Year/Month'], format='%Y/%m')
df['Year'] = df['Year/Month'].dt.year
df['Month'] = df['Year/Month'].dt.month

# Drop the original 'Year/Month' column
#df.drop(columns=['Year/Month'], inplace=True)

# Check for any NaN values after pivoting
print(df.isna().sum())

# Handle missing values
df.fillna(method='ffill', inplace=True)

  Year/Month Box Size  Longitude  Latitude PID2: Standard/Enhanced Group  \
0     1857/1        2      276.0       6.0                       0     3
0     1858/1        2      352.0      44.0                       0     3
1     1858/1        2      334.0       8.0                       0     3
0     1858/2        2      302.0      24.0                       0     3
1     1858/2        2      332.0      10.0                       0     3

  Checksum   S-S1  S-Median  S-S5  ...  R-S1 R-Median  R-S5 R-Mean  \
0       14  26.10      26.1  26.1  ...  65.6     65.6  65.6   65.6
0        7  11.70      11.7  11.7  ...  91.6     91.6  91.6   91.6
1        8  25.00      25.6  25.6  ...  83.4     83.4  83.4   83.4
0        2  21.10      21.1  21.1  ...  58.9     58.9  58.9   58.9
1        4  23.67      23.9  25.7  ...  66.4     66.4  66.4   66.4

   R-Observation number  R-Standard deviation  R-Mean day of the month  \
0                     1                   0.0                       16
0                     1                   0.0                       18
1                     1                   0.0                       26
0                     1                   0.0                       24
1                     1                   0.0                       10

   R-Fraction of daylight observations  R-Mean Longitude  R-Mean Latitude
0                                  1.0               0.8              0.8
0                                  0.0               0.1              0.8
1                                  0.0               0.3              0.2
0                                  0.0               0.6              0.3
1                                  1.0               0.3              0.0

[5 rows x 47 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 5078925 entries, 0 to 4466
Data columns (total 47 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Year/Month                           object
 1   Box Size                             object
 2   Longitude                            float64
 3   Latitude                             float64
 4   PID2: Standard/Enhanced              object
 5   Group                                object
 6   Checksum                             object
 7   S-S1                                 float64
 8   S-Median                             float64
 9   S-S5                                 float64
 10  S-Mean                               float64
 11  S-Observation number                 object
 12  S-Standard deviation                 float64
 13  S-Mean day of the month              object
 14  S-Fraction of daylight observations  float64
 15  S-Mean Longitude                     float64
 16  S-Mean Latitude                      float64
 17  A-S1                                 float64
 18  A-Median                             float64
 19  A-S5                                 float64
 20  A-Mean                               float64
 21  A-Observation number                 object
 22  A-Standard deviation                 float64
 23  A-Mean day of the month              object
 24  A-Fraction of daylight observations  float64
 25  A-Mean Longitude                     float64
 26  A-Mean Latitude                      float64
 27  Q-S1                                 float64
 28  Q-Median                             float64
 29  Q-S5                                 float64
 30  Q-Mean                               float64
 31  Q-Observation number                 object
 32  Q-Standard deviation                 float64
 33  Q-Mean day of the month              object
 34  Q-Fraction of daylight observations  float64
 35  Q-Mean Longitude                     float64
 36  Q-Mean Latitude                      float64
 37  R-S1                                 float64
 38  R-Median                             float64
 39  R-S5                                 float64
 40  R-Mean                               float64
 41  R-Observation number                 object
 42  R-Standard deviation                 float64
 43  R-Mean day of the month              object
 44  R-Fraction of daylight observations  float64
 45  R-Mean Longitude                     float64
 46  R-Mean Latitude                      float64
dtypes: float64(34), object(13)
memory usage: 1.8+ GB
None
          Longitude      Latitude          S-S1      S-Median          S-S5  \
count  5.078925e+06  5.078925e+06  5.078925e+06  5.078925e+06  5.078925e+06
mean   1.980270e+02  8.182723e+00  2.006752e+01  2.084752e+01  2.162016e+01
std    1.015496e+02  3.068758e+01  7.751360e+00  7.623786e+00  7.516001e+00
min    0.000000e+00 -7.800000e+01 -2.800000e+00 -2.800000e+00 -2.800000e+00
25%    1.220000e+02 -1.600000e+01  1.509000e+01  1.610000e+01  1.700000e+01
50%    1.980000e+02  1.000000e+01  2.224000e+01  2.310000e+01  2.398000e+01
75%    2.940000e+02  3.400000e+01  2.652000e+01  2.700000e+01  2.780000e+01
max    3.580000e+02  8.000000e+01  3.600000e+01  3.610000e+01  3.670000e+01

             S-Mean  S-Standard deviation  \
count  5.078925e+06          5.078925e+06
mean   2.084201e+01          9.485283e-01
std    7.604378e+00          7.026779e-01
min   -2.800000e+00          0.000000e+00
25%    1.610000e+01          4.500000e-01
50%    2.312000e+01          9.200000e-01
75%    2.710000e+01          1.330000e+00
max    3.600000e+01          1.414000e+01

       S-Fraction of daylight observations  S-Mean Longitude  S-Mean Latitude  \
count                         5.078925e+06      5.078925e+06     5.078925e+06
mean                          5.347744e-01      5.057406e-01     4.959933e-01
std                           2.864837e-01      1.796350e-01     2.004967e-01
min                           0.000000e+00      0.000000e+00     0.000000e+00
25%                           4.000000e-01      4.000000e-01     4.000000e-01
50%                           5.000000e-01      5.000000e-01     5.000000e-01
75%                           7.000000e-01      6.000000e-01     6.000000e-01
max                           1.000000e+00      1.000000e+00     1.000000e+00

       ...  Q-Mean Longitude  Q-Mean Latitude          R-S1      R-Median  \
count  ...      5.078925e+06     5.078925e+06  5.078925e+06  5.078925e+06
mean   ...      5.056348e-01     4.957735e-01  7.471220e+01  8.060864e+01
std    ...      1.903644e-01     2.106548e-01  8.936466e+00  7.647170e+00
min    ...      0.000000e+00     0.000000e+00  1.530000e+01  1.530000e+01
25%    ...      4.000000e-01     4.000000e-01  6.890000e+01  7.600000e+01
50%    ...      5.000000e-01     5.000000e-01  7.440000e+01  8.060000e+01
75%    ...      6.000000e-01     6.000000e-01  8.010000e+01  8.530000e+01
max    ...      1.000000e+00     1.000000e+00  1.000000e+02  1.000000e+02

               R-S5        R-Mean  R-Standard deviation  \
count  5.078925e+06  5.078925e+06          5.078925e+06
mean   8.606737e+01  8.038503e+01          6.817307e+00
std    7.770283e+00  7.174450e+00          4.604985e+00
min    1.530000e+01  1.530000e+01          0.000000e+00
25%    8.180000e+01  7.610000e+01          3.400000e+00
50%    8.680000e+01  8.040000e+01          7.100000e+00
75%    9.150000e+01  8.470000e+01          1.000000e+01
max    1.000000e+02  1.000000e+02          5.320000e+01

       R-Fraction of daylight observations  R-Mean Longitude  R-Mean Latitude
count                         5.078925e+06      5.078925e+06     5.078925e+06
mean                          5.343510e-01      5.055620e-01     4.956691e-01
std                           3.047356e-01      1.882669e-01     2.088247e-01
min                           0.000000e+00      0.000000e+00     0.000000e+00
25%                           3.000000e-01      4.000000e-01     4.000000e-01
50%                           5.000000e-01      5.000000e-01     5.000000e-01
75%                           7.000000e-01      6.000000e-01     6.000000e-01
max                           1.000000e+00      1.000000e+00     1.000000e+00

[8 rows x 34 columns]

Year/Month                             0
Box Size                               0
Longitude                              0
Latitude                               0
PID2: Standard/Enhanced                0
Group                                  0
Checksum                               0
S-S1                                   0
S-Median                               0
S-S5                                   0
S-Mean                                 0
S-Observation number                   0
S-Standard deviation                   0
S-Mean day of the month                0
S-Fraction of daylight observations    0
S-Mean Longitude                       0
S-Mean Latitude                        0
A-S1                                   0
A-Median                               0
A-S5                                   0
A-Mean                                 0
A-Observation number                   0
A-Standard deviation                   0
A-Mean day of the month                0
A-Fraction of daylight observations    0
A-Mean Longitude                       0
A-Mean Latitude                        0
Q-S1                                   0
Q-Median                               0
Q-S5                                   0
Q-Mean                                 0
Q-Observation number                   0
Q-Standard deviation                   0
Q-Mean day of the month                0
Q-Fraction of daylight observations    0
Q-Mean Longitude                       0
Q-Mean Latitude                        0
R-S1                                   0
R-Median                               0
R-S5                                   0
R-Mean                                 0
R-Observation number                   0
R-Standard deviation                   0
R-Mean day of the month                0
R-Fraction of daylight observations    0
R-Mean Longitude                       0
R-Mean Latitude                        0
dtype: int64

In [ ]:
# Split features and target
X = df[['Year', 'Month', 'Longitude', 'Latitude', 'A-Mean', 'Q-Mean', 'R-Mean']].values  # Features
y = df[['S-Mean']].values  # Targets

# Check for NaN or infinite values in targets
print("NaN values in y:", np.isnan(y).sum())
print("Infinite values in y:", np.isinf(y).sum())

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features using RobustScaler
scaler = RobustScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check for NaN values in scaled features
print("NaN values in X_train:", np.isnan(X_train).sum())
print("NaN values in X_test:", np.isnan(X_test).sum())

print(X_train.shape[1])

In [ ]:
# Define the model
model = Sequential()
model.add(Dense(2, input_dim=X_train.shape[1], activation='relu'))
model.add(BatchNormalization())
model.add(Dense(2, activation='relu'))
model.add(BatchNormalization())
model.add(Dense(y_train.shape[1]))  # Output layer with 4 neurons for Mean_S, Mean_A, Mean_Q, Mean_R
model.summary()

# Compile the model with a lower learning rate
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

# Train the model
history = model.fit(X_train, y_train, epochs=50, batch_size=128, validation_split=0.2)

# Evaluate the model
loss, mae = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss}")
print(f"Test MAE: {mae}")

# Plot training & validation MAE values
plt.plot(history.history['mae'])
plt.plot(history.history['val_mae'])
plt.title('Model MAE')
plt.ylabel('Mean Absolute Error')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

# Plot training & validation loss values
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

In [ ]:
model.save('G3_S_model.keras')